info:
  name: ${project.artifactId}
  version: ${project.version}
  origin: ${scm.url}
  commit: ${buildNumber}
  branch: ${scmBranch}
  built: ${timestamp}

# logging config here as a reminder as to how to override logback from cmd line
# ie -Dlogging.level.org.springframework=DEBUG
logging:
  level:
    com.example: DEBUG
    org.springframework: WARN
  profile: DEV

security:
  basic:
    enabled: false
    realm: sdc
  user:
    name: admin
    password: secret

management:
  security:
    roles: SUPERUSER
    enabled: true
  health:
    rabbit:
      enabled: false

server:
  port: 8171
  servlet-path: /

endpoints:
  enabled: true
  info:
    enabled: true
    sensitive: false

spring:
  output:
    ansi:
      enabled: never
  application:
    name: SpringBoot Service
